# Generated by Django 5.1 on 2024-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала акции')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания акции')),
                ('dishes', models.ManyToManyField(related_name='promotions', to='menu.dish')),
            ],
        ),
    ]
