# Generated by Django 5.1 on 2024-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_category_description'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='description',
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='menu.dish', verbose_name='Блюда в акции'),
        ),
    ]
