# Generated by Django 5.1 on 2024-08-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
